#!/usr/bin/env python3
"""Generates the Big5-HKSCS decode table used by the CWMoney CSV importer.

Dart has no built-in Big5 codec, and CWMoney exports need the HKSCS
extension (plain CP950 fails on real files). Python's `big5hkscs` codec is
the reference; this script snapshots it into a Dart source file.

Layout: for every double-byte code (lead 0x81-0xFE, trail 0x40-0x7E or
0xA1-0xFE) two UTF-16 code units are stored. [0, 0] means unmapped; a
second unit of 0 means the code maps to a single BMP code unit.

Usage: python3 tool/gen_big5hkscs_table.py > \
  packages/aura_core/lib/src/interop/cwmoney/big5hkscs_table.g.dart
"""
import base64
import struct

TRAILS = list(range(0x40, 0x7F)) + list(range(0xA1, 0xFF))

units = []
for lead in range(0x81, 0xFF):
    for trail in TRAILS:
        try:
            text = bytes([lead, trail]).decode("big5hkscs")
        except UnicodeDecodeError:
            units += [0, 0]
            continue
        cu = struct.unpack("<%dH" % (len(text.encode("utf-16-le")) // 2), text.encode("utf-16-le"))
        assert 1 <= len(cu) <= 2, (hex(lead), hex(trail), text)
        units += [cu[0], cu[1] if len(cu) == 2 else 0]

blob = base64.b64encode(struct.pack("<%dH" % len(units), *units)).decode()
lines = [blob[i:i + 76] for i in range(0, len(blob), 76)]
print("// GENERATED by tool/gen_big5hkscs_table.py. Do not edit.")
print("// Source: Python big5hkscs codec. %d trail bytes per lead byte." % len(TRAILS))
print()
print("const big5HkscsTableBase64 =")
for i, line in enumerate(lines):
    print("    '%s'%s" % (line, ";" if i == len(lines) - 1 else ""))
